# Generated by Django 3.2.17 on 2023-02-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_movie_id_comment_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content_id',
            field=models.BigIntegerField(max_length=255),
        ),
    ]
