movie = {
    "adult": False,
    "backdrop_path": "/bT3IpP7OopgiVuy6HCPOWLuaFAd.jpg",
    "belongs_to_collection": {
        "id": 929336,
        "name": "Murder Mystery Collection",
        "poster_path": "/tXvqgUtguLjVVYqyAOy0eYtm5lH.jpg",
        "backdrop_path": "/dsHP6PVJkMuJgftxHMHAhnYNqtG.jpg",
    },
    "budget": 0,
    "genres": [
        {"id": 35, "name": "Comedy"},
        {"id": 9648, "name": "Mystery"},
        {"id": 28, "name": "Action"},
    ],
    "homepage": "https://www.netflix.com/title/81212842",
    "id": 638974,
    "imdb_id": "tt15255288",
    "original_language": "en",
    "original_title": "Murder Mystery 2",
    "overview": "After starting their own detective agency, Nick and Audrey Spitz land a career-making case when their billionaire pal is kidnapped from his wedding.",
    "popularity": 1855.858,
    "poster_path": "/s1VzVhXlqsevi8zeCMG9A16nEUf.jpg",
    "production_companies": [
        {
            "id": 878,
            "logo_path": "/e2AZdsQdkhN0qJhoN4TMYiVPLyb.png",
            "name": "Happy Madison Productions",
            "origin_country": "US",
        },
        {
            "id": 7382,
            "logo_path": "/vW2v0PPCDsp3qbB7aXRVavhxmu6.png",
            "name": "Echo Films",
            "origin_country": "US",
        },
        {"id": 19367, "logo_path": None, "name": "Vinson Films", "origin_country": ""},
        {
            "id": 1205,
            "logo_path": "/wQX3t4qtxm7gBQE3RHuoLghgb73.png",
            "name": "Endgame Entertainment",
            "origin_country": "US",
        },
    ],
    "production_countries": [{"iso_3166_1": "US", "name": "United States of America"}],
    "release_date": "2023-03-28",
    "revenue": 0,
    "runtime": 91,
    "spoken_languages": [
        {"english_name": "English", "iso_639_1": "en", "name": "English"}
    ],
    "status": "Released",
    "tagline": "This mystery is deux or die.",
    "title": "Murder Mystery 2",
    "video": False,
    "vote_average": 6.558,
    "vote_count": 858,
}
